export const ALL_PROJECT_REQUEST = "ALL_PROJECT_REQUEST"
export const ALL_PROJECT_SUCCESS = "ALL_PROJECT_SUCCESS"
export const ALL_PROJECT_FAIL = "ALL_PROJECT_FAIL"


export const PROJECT_DETAILS_REQUEST = "PROJECT_DETAILS_REQUEST"
export const PROJECT_DETAILS_SUCCESS = "PROJECT_DETAILS_SUCCESS"
export const PROJECT_DETAILS_FAIL = "PROJECT_DETAILS_FAIL"


export const LOGIN_REQUEST = "LOGIN_REQUEST"
export const LOGIN_SUCCESS = "LOGIN_SUCCESS"
export const LOGIN_FAIL = "LOGIN_FAIL"
export const LOGIN_AFTER_OTPVERIFICATION = "LOGIN_AFTER_OTPVERIFICATION "


export const LOGOUT_REQUEST =  "LOGOUT_REQUEST"
export const LOGOUT_SUCCESS =  "LOGOUT_SUCCESS"
export const LOGOUT_FAIL =  "LOGOUT_FAIL"


export const REGISTER_REQUEST = "REGISTER_REQUEST"
export const REGISTER_SUCCESS = "REGISTER_SUCCESS"
export const REGISTER_FAIL = "REGISTER_FAIL"

export const LOGIN_RESET = "LOGIN_RESET"

export const REGISTERED_LOGIN = "REGISTERED_LOGIN"


export const ADD_REVIEW_REQUEST = "ADD_REVIEW_REQUEST"
export const ADD_REVIEW_SUCCESS = "ADD_REVIEW_SUCCESS"
export const ADD_REVIEW_FAIL = "ADD_REVIEW_FAIL"

export const GET_ALL_REVIEWS_REQUEST = "GET_ALL_REVIEWS_REQUEST"
export const GET_ALL_REVIEWS_SUCCESS = "GET_ALL_REVIEWS_SUCCESS"
export const GET_ALL_REVIEWS_FAIL = "GET_ALL_REVIEWS_FAIL"


export const EDIT_DETAILS_REQUEST = "EDIT_DETAILS_REQUEST"
export const EDIT_DETAILS_SUCCESS = "EDIT_DETAILS_SUCCESS"
export const EDIT_DETAILS_FAIL = "EDIT_DETAILS_FAIL"


export const GET_USER_DETAILS_REQUEST = "GET_USER_DETAILS_REQUEST"
export const GET_USER_DETAILS_SUCCESS = "GET_USER_DETAILS_SUCCESS"
export const GET_USER_DETAILS_FAIL = "GET_USER_DETAILS_FAIL"
export const GET_USER_DETAILS_RESET = "GET_USER_DETAILS_RESET"

export const GET_EDITED_USER_DETAILS_REQUEST = "GET_EDITED_USER_DETAILS_REQUEST"

export const UPDATE_PASSWORD_REQUEST = "UPDATE_PASSWORD_REQUEST"
export const UPDATE_PASSWORD_SUCCESS = "UPDATE_PASSWORD_SUCCESS"
export const UPDATE_PASSWORD_FAIL = "UPDATE_PASSWORD_FAIL"

export const UPDATE_PASSWORD_RESET = "UPDATE_PASSWORD_RESET"

export const EDIT_PROFILE_RESET = "EDIT_PROFILE_RESET"


export const GET_USER_ALL_PROJECT_REQUEST = "GET_USER_ALL_PROJECT_REQUEST"
export const GET_USER_ALL_PROJECT_SUCCESS = "GET_USER_ALL_PROJECT_SUCCESS"
export const GET_USER_ALL_PROJECT_FAIL = "GET_USER_ALL_PROJECT_FAIL"


export const DELETE_PROJECT_USER_REQUEST = "DELETE_PROJECT_USER_REQUEST"
export const DELETE_PROJECT_USER_SUCCESS = "DELETE_PROJECT_USER_SUCCESS"
export const DELETE_PROJECT_USER_FAIL = "DELETE_PROJECT_USER_FAIL"
export const DELETE_PROJECT_USER_RESET = "DELETE_PROJECT_USER_RESET"

export const GET_USER_ALL_PROJECT_AFTER_DELETION = "GET_USER_ALL_PROJECT_AFTER_DELETION"

export const EDIT_PROJECT_REQUEST = "EDIT_PROJECT_REQUEST"
export const EDIT_PROJECT_SUCCESS = "EDIT_PROJECT_SUCCESS"
export const EDIT_PROJECT_FAIL = "EDIT_PROJECT_FAIL"


export const EDIT_PROJECT_RESET = "EDIT_PROJECT_RESET"

export const SELL_PROJECT_REQUEST = "SELL_PROJECT_REQUEST"
export const SELL_PROJECT_SUCCESS = "SELL_PROJECT_SUCCESS"
export const SELL_PROJECT_FAIL = "SELL_PROJECT_FAIL"
export const SELL_PROJECT_RESET = "SELL_PROJECT_RESET"


export const BUY_PROJECT_REQUEST = "BUY_PROJECT_REQUEST"
export const BUY_PROJECT_SUCCESS = "BUY_PROJECT_SUCCESS"
export const BUY_PROJECT_FAIL = "BUY_PROJECT_FAIL"

export const BUY_PROJECT_RESET = "BUY_PROJECT_RESET"


export const OTP_VERIFICATION_REQUEST = "OTP_VERIFICATION_REQUEST"
export const OTP_VERIFICATION_SUCCESS = "OTP_VERIFICATION_SUCCESS"
export const OTP_VERIFICATION_FAIL = "OTP_VERIFICATION_FAIL"

export const FORGET_PASSWORD_REQUEST = "FORGET_PASSWORD_REQUEST"
export const FORGET_PASSWORD_SUCCESS = "FORGET_PASSWORD_SUCCESS"
export const FORGET_PASSWORD_FAIL = "FORGET_PASSWORD_FAIL"

export const RESET_PASSWORD_REQUEST = "RESET_PASSWORD_REQUEST"
export const RESET_PASSWORD_SUCCESS = "RESET_PASSWORD_SUCCESS"
export const RESET_PASSWORD_FAIL = "RESET_PASSWORD_FAIL"
export const RESET_PASSWORD_CHANGE = "RESET_PASSWORD_CHANGE"

